"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads environment variables from .env (never versioned)
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default):
    """Reads a boolean from the environment accepting 1/true/yes."""
    return os.environ.get(name, default).strip().lower() in ('1', 'true', 'yes')


def env_int(name, default):
    """Reads an integer from the environment, falling back on invalid values."""
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return int(default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k5xz(fy1p7$17^c5x545wyz8fbx#r3zv6b4exe^&pgu5%dv64u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'accounts',
    'ai',
    'categories',
    'profiles',
    'transactions',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH') or BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Custom user model
AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Security headers
SECURE_BROWSER_XSS_FILTER = True
X_CONTENT_TYPE_OPTIONS = 'nosniff'
SECURE_CONTENT_TYPE_NOSNIFF = True

# AI financial analysis agent (app 'ai')
# The API key must come from the environment / .env — never commit it.
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')

# Model identifier used by ChatDeepSeek (see DeepSeek docs for the current id)
DEEPSEEK_MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-chat')

# Feature flag: the agent stays off while there is no API key configured
AI_ANALYSIS_ENABLED = env_bool('AI_ANALYSIS_ENABLED', 'True') and bool(DEEPSEEK_API_KEY)

# Minimum gap between on-demand analyses of the same user, in minutes
AI_ANALYSIS_MIN_INTERVAL_MINUTES = env_int('AI_ANALYSIS_MIN_INTERVAL_MINUTES', 15)

# Timeout of a single agent run, in seconds
AI_AGENT_TIMEOUT_SECONDS = env_int('AI_AGENT_TIMEOUT_SECONDS', 60)

# Maximum number of model calls in the agent loop
AI_AGENT_MAX_ITERATIONS = env_int('AI_AGENT_MAX_ITERATIONS', 10)

# Default window of months considered by the analysis
AI_ANALYSIS_MONTHS_WINDOW = env_int('AI_ANALYSIS_MONTHS_WINDOW', 6)
