# Generated by Django 6.0.3 on 2026-08-02 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], max_length=10, verbose_name='Situação')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('insights', models.JSONField(blank=True, default=list, verbose_name='Insights')),
                ('tips', models.JSONField(blank=True, default=list, verbose_name='Dicas')),
                ('health_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Índice de saúde financeira')),
                ('health_label', models.CharField(blank=True, choices=[('critical', 'Crítica'), ('attention', 'Atenção'), ('good', 'Boa'), ('excellent', 'Excelente')], max_length=20, verbose_name='Classificação da saúde financeira')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Início do período analisado')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fim do período analisado')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de saída')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens totais')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duração (ms)')),
                ('iterations', models.PositiveSmallIntegerField(default=0, verbose_name='Iterações')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Análise de IA',
                'verbose_name_plural': 'Análises de IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_analysis_user_recent')],
            },
        ),
    ]
